### PR TITLE
Enable ironic cleaning

### PR DESCRIPTION
**Pull request by jtaleric**
Enable ironic to clean disk metadata only.

### CODE REVIEW

**Comment by jtaleric** [comment]
I wonder if we just need to add a new state?
```go
// Change a node to "available" state
func (workflow *provisionStateWorkflow) toAvailable() (done bool, err error) {
        switch state := workflow.d.Get("provision_state").(string); state {
        case "available":
                // We're done!
                return true, nil
        case "cleaning":
                // Not done, no error - Ironic is working
                log.Printf("[DEBUG] Node %s is '%s', waiting for Ironic to finish.", workflow.d.Id(), state)
                return false, nil
        case "manageable":
                // From manageable, we can go to provide
                log.Printf("[DEBUG] Node %s is '%s', going to change to 'available'", workflow.d.Id(), state)
                return workflow.changeProvisionState(nodes.TargetProvide)
        default:
                // Otherwise we have to get into manageable state first
                log.Printf("[DEBUG] Node %s is '%s', going to change to 'manageable'.", workflow.d.Id(), state)
                _, err := workflow.toManageable()
                if err != nil {
                        return true, err
                }
                return false, nil
        }

        return false, nil
}

```

**Comment by jtaleric** [comment]
@stbenjam Would you happen to know? ^

**Comment by stbenjam** [comment]
Yes, that's all it needs.

**Comment by stbenjam** [comment]
https://github.com/openshift-metalkube/terraform-provider-ironic/pull/16

**Comment by stbenjam** [comment]
The installer needs an update to pull in the new terraform provider - that's here, https://github.com/openshift-metalkube/kni-installer/pull/45. You can test this updated container with that, it should work now.

I also filed https://github.com/openshift-metalkube/terraform-provider-ironic/issues/17 for me to ensure I handle all the possible state transitions, there's a few more that aren't covered, mostly `xyz failed` states.

**Comment by bfournie** [comment]
With the terraform change to add support for clean-wait this should fe fine.

**Comment by stbenjam** [comment]
I’d not merge this until the installer change is in

**Comment by jtaleric** [comment]
@bfournie What else is holding this up?

**Comment by stbenjam** [comment]
https://github.com/openshift-metalkube/kni-installer/pull/45 has been merged, this should be good to go.

**Pull request merged**
