### PR TITLE
Configure httpd to listen on 5280 instead of 80.

### PR DESCRIPTION
**Pull request by imain**
I just picked the port at random.  Kubernetes definitely has things running on port 80 so we gotta move this. 
 Hopefully this is all that needs changing.  Let me know! :)

### CODE REVIEW

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/257/

**Comment by dtantsur** [comment]
We'll also have to update https://github.com/openshift-metalkube/dev-scripts/blob/master/ironic/dnsmasq.conf#L10. And no, I don't know why it's in dev-scripts rather than here :)

**Comment by dtantsur** [comment]
Got it, let's rebase it on top of #15.

**Comment by imain** [comment]
Do you mean apply 15 on top of this one?  That is what I would expect..

**Comment by dtantsur** [comment]
No, the other way around. Otherwise this change is breaking because port 80 is still used in dnsmasq configuration.

**Comment by imain** [comment]
Bob is going to take this on.  Thanks again Bob!!

**Pull request closed without merging**
